name: Call Authorize Commit Signing

on: [push]

jobs:
  call-bi-workflow-passing-repository-name:
    uses: bipl/.github/workflows/auth-commit-sig.yml@main
    with:
      repository-name: cloudpki/rradmin
    secrets: inherit
